// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnsfnmjuelrkgbnghumc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFuc2ZubWp1ZWxya2dibmdodW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTA5NjksImV4cCI6MjA2Njc2Njk2OX0.HDzyVFxUNUZ6HPMEddWDOR5jfwt2J16Jy1MgVoseArI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);